# Generated by Django 5.0.4 on 2024-08-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
