# Generated by Django 5.0.4 on 2024-08-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='applicable_for',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='describe',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='propose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
