# Generated by Django 5.0.4 on 2024-08-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_url',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
