# Generated by Django 5.0.4 on 2024-08-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_news_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
